### ISSUE TITLE
[CI] Run check_output script on new stubs build

### ISSUE THREAD

**Issue by vemel** [vemel/mypy_boto3_builder#93]
**Describe your idea**

There is `./scripts/check_output.py` script that checks generated packages with `flake8` and `pyright`. The idea is to run the script once new version of `boto3-stubs` and subpackages are built in `publish_boto3_stubs.yml` workflow.

**Code sample**

```yaml
      - name: Check generated packages
        run: |
          python ./scripts/install.py master
          python ./scripts/check_output.py
```
